variables:
  GIT_STRATEGY: clone

stages:
  - deploy
  - test

deploy_servlet:
  stage: deploy
  script:
        - ./deploy.sh
  only:
      - master
  environment:
        name: prd

test_servlet:
  stage: test
  environment:
        name: prd
  script:
        - ./test.sh
